### ISSUE TITLE
Website will not allow Firefox to display the page if another site has embedded it

### ISSUE THREAD

**Issue by feinstaub** [klimadashboard/.github#1]
Hallo zusammen,
tolle Seite, die ihr da zusammengestellt habt! Wirklich sehr hilfreich!
Wir wollen das CO2-Budget-Diagramm bei uns https://www.bund-bergstrasse.de/ einbetten und haben dazu von https://klimadashboard.de/emissionen/co2-budget folgenden Code kopiert:

`<iframe src="https://klimadashboard.de/embed/DdNq4GEZCdLZjnUz" width=400 height=400>`

Die Fehlermeldung, die Firefox dann im Frame anzeigt, ist diese: "Website will not allow Firefox to display the page if another site has embedded it"

Könnt ihr da weiterhelfen?

Danke & Grüße

**Comment by davidjablonski** [comment]
Danke für den Hinweis, wir haben die Konfiguration von unserem Server angepasst und die Einbettung sollte jetzt korrekt funktionieren. Falls dem nicht so ist, gern nochmals Bescheid geben.

**Comment by feinstaub** [comment]
Klasse, danke für die schnelle Reaktion! Der Inhalt wird nun angezeigt.
Leider ist auf der Webseite alles unter dem iframe abgeschnitten (als käme da kein weitere Inhalt). Das liegt möglicherweise an unserem CMS.
